name: Build SMS Relay APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # STEP 1: checkout repo
      - name: Checkout repo
        uses: actions/checkout@v4

      # STEP 2: setup Java (Gradle butuh JDK)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      # STEP 3: setup Android SDK base
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      # STEP 4: install platform + build-tools yg kita butuh
      - name: Install required Android SDK packages
        run: |
          sdkmanager --install "platform-tools" "platforms;android-34" "build-tools;34.0.0"
          yes | sdkmanager --licenses

      # STEP 5: debug env (biar kelihatan versi gradle, java, dll saat gagal)
      - name: Env debug info
        run: |
          echo "java version:"
          java -version
          echo "gradle version:"
          gradle -v || true
          echo "ls repo:"
          ls -R .

      # STEP 6: build APK (Debug)
      # pakai gradle langsung, karena project kamu belum punya gradlew wrapper
      - name: Build APK (assembleDebug)
        run: |
          gradle assembleDebug

      # STEP 7: upload APK hasil build sebagai artifact ke tab Actions
      - name: Upload APK artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: SmsRelay-APK
          path: app/build/outputs/apk/debug/app-debug.apk
